config/routes.rb
Rails.application.routes.draw do
  resources :financers
  resources :individuals
  resources :companies
  resources :my_customers

end

app/models/my_customer.rb
class MyCustomer < ActiveRecord::Base
  belongs_to :tradeable, polymorphic: true
  validates :tradeable, presence: true
  validates :number, presence: true

  TRADEABLE_TYPES = ["Company", "Individual", "Financer"]

end

app/controllers/my_customers_controller.rb
class MyCustomersController < ApplicationController
  before_action :set_my_customer, only: [:show, :edit, :update, :destroy]

  # GET /my_customers
  # GET /my_customers.json
  def index
    @my_customers = MyCustomer.all
  end

  # GET /my_customers/1
  # GET /my_customers/1.json
  def show
  end

  # GET /my_customers/new
  def new
    @my_customer = MyCustomer.new
    @company = Company.new
    @financer = Financer.new
    @individual = Individual.new
  end

  # GET /my_customers/1/edit
  def edit
    @company = @my_customer.tradeable.class == Company ? @my_customer.tradeable : Company.new
    @financer = @my_customer.tradeable if @my_customer.tradeable.class == Financer
    @financer ||= Financer.new
    @individual = @my_customer.tradeable if @my_customer.tradeable.class == Individual
    @individual ||= Individual.new
  end

  # POST /my_customers
  # POST /my_customers.json
  def create
    saved = false
    begin
      ActiveRecord::Base.transaction do
        @my_customer = MyCustomer.new(my_customer_params)
        if params[:my_customer][:tradeable_type] == "Company"
          @company = Company.new(company_params)
          @company.save!
          @my_customer = @company
        elsif params[:my_customer][:tradeable_type] == "Financer"
          @financer = Financer.new(financer_params)
          @financer.save!
          @my_customer = @financer
        elsif params[:my_customer][:tradeable_type] == "Individual"
          @individual = Individual.new(individual_params)
          @individual.save!
          @my_customer = @individual
        end
        @my_customer.save!
        saved = true
      end
    rescue ActiveRecord::RecordInvalid
    end


    respond_to do |format|
      if saved
        format.html { redirect_to @my_customer, notice: 'My customer was successfully created.' }
        format.json { render :show, status: :created, location: @my_customer }
      else
        format.html { render :new }
        format.json { render json: @my_customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_customers/1
  # PATCH/PUT /my_customers/1.json
  def update
    respond_to do |format|
      if @my_customer.update(my_customer_params)
        format.html { redirect_to @my_customer, notice: 'My customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @my_customer }
      else
        format.html { render :edit }
        format.json { render json: @my_customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_customers/1
  # DELETE /my_customers/1.json
  def destroy
    @my_customer.destroy
    respond_to do |format|
      format.html { redirect_to my_customers_url, notice: 'My customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_customer
      @my_customer = MyCustomer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_customer_params
      params.require(:my_customer).permit(:number)
    end

    def financer_params
      params.require(:financer).permit(:name)
    end

    def individual_params
      params.require(:individual).permit(:first_name, :last_name)
    end

    def company_params
      params.require(:company).permit(:tax_number, :name)
    end
end

app/helpers/my_customers_helper.rb
module MyCustomersHelper
end

app/views/my_customers/_form.html.erb
<%= form_for(@my_customer) do |f| %>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_area :number %>
  </div>
  <div class="field">
    <%= f.label :tradeable_type %><br>
    <%= f.select :tradeable_type, MyCustomer::TRADEABLE_TYPES %>
  </div>
  <div id="tradeable-form">

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
  var company_form = "<%= escape_javascript(render 'companies/partial_form') %>"
  var financer_form = "<%= escape_javascript(render 'financers/partial_form') %>"
  var individual_form = "<%= escape_javascript(render 'individuals/partial_form') %>"
  var tradeable_type_changed = function(type){
    if (type == "Company") {
      $('#tradeable-form').html(company_form)
    } else if (type == "Individual") {
      $('#tradeable-form').html(individual_form)
    } else if (type == "Financer") {
      $('#tradeable-form').html(financer_form)
    } else {
      $('#tradeable-form').html("")
    }
  }
  tradeable_type_changed($("#my_customer_tradeable_type").val())
  $("#my_customer_tradeable_type").on('change',function(){
    var current_type = $(this).val();
    tradeable_type_changed(current_type)
  })
</script>

app/views/my_customers/edit.html.erb
<h1>Editing My Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @my_customer %> |
<%= link_to 'Back', my_customers_path %>

app/views/my_customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing My Customers</h1>

<%= link_to 'New My customer', new_my_customer_path %>
<%= link_to "New Company", new_company_path %>
<%= link_to "New Individual", new_individual_path %>
<%= link_to "New Financer", new_financer_path %>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Tradeable</th>
      <th>Tradeable type</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_customers.each do |my_customer| %>
      <tr>
        <td><%= my_customer.number %></td>
        <td><%= my_customer.tradeable_id %></td>
        <td><%= my_customer.tradeable_type %></td>
        <td><%= my_customer.tradeable.description %></td>
        <td><%= link_to 'Show', my_customer %></td>
        <td><%= link_to 'Edit', edit_my_customer_path(my_customer) %></td>
        <td><%= link_to 'Destroy', my_customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/my_customers/new.html.erb
<h1>New My Customer</h1>

<%= render 'form' %>

<%= link_to 'Back', my_customers_path %>

app/views/my_customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @my_customer.number %>
</p>

<p>
  <strong>Tradeable:</strong>
  <%= @my_customer.tradeable_id %>
</p>

<p>
  <strong>Tradeable type:</strong>
  <%= @my_customer.tradeable_type %>
</p>

<%= link_to 'Edit', edit_my_customer_path(@my_customer) %> |
<%= link_to 'Back', my_customers_path %>