config/routes.rb
Rails.application.routes.draw do
  resources :financers
  resources :individuals
  resources :companies
  resources :my_customers

end

app/models/financer.rb
class Financer < ActiveRecord::Base
  has_one :my_customer, as: :tradeable
  after_save :ensure_my_customer

  def ensure_my_customer
    if self.my_customer.nil?
      my_customer = MyCustomer.new(number: "#{self.class}-#{self.class.count}")
      my_customer.tradeable = self
      my_customer.save!
    end
  end

  def description
    "#{self.name}"
  end

end

app/controllers/financers_controller.rb
class FinancersController < ApplicationController
  before_action :set_financer, only: [:show, :edit, :update, :destroy]

  # GET /financers
  # GET /financers.json
  def index
    @financers = Financer.all
  end

  # GET /financers/1
  # GET /financers/1.json
  def show
  end

  # GET /financers/new
  def new
    @financer = Financer.new
  end

  # GET /financers/1/edit
  def edit
  end

  # POST /financers
  # POST /financers.json
  def create
    saved = false
    begin
      ActiveRecord::Base.transaction do
        @financer = Financer.new(financer_params)
        @financer.save!
        saved = true
      end
    rescue ActiveRecord::RecordInvalid
    end

    respond_to do |format|
      if saved
        format.html { redirect_to @financer, notice: 'Financer was successfully created.' }
        format.json { render :show, status: :created, location: @financer }
      else
        format.html { render :new }
        format.json { render json: @financer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /financers/1
  # PATCH/PUT /financers/1.json
  def update
    respond_to do |format|
      if @financer.update(financer_params)
        format.html { redirect_to @financer, notice: 'Financer was successfully updated.' }
        format.json { render :show, status: :ok, location: @financer }
      else
        format.html { render :edit }
        format.json { render json: @financer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /financers/1
  # DELETE /financers/1.json
  def destroy
    @financer.destroy
    respond_to do |format|
      format.html { redirect_to financers_url, notice: 'Financer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_financer
      @financer = Financer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def financer_params
      params.require(:financer).permit(:name)
    end
end

app/helpers/financers_helper.rb
module FinancersHelper
end

app/views/financers/_form.html.erb
<%= form_for(@financer) do |f| %>
  <% if @financer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@financer.errors.count, "error") %> prohibited this financer from being saved:</h2>

      <ul>
      <% @financer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/financers/_partial_form.html.erb
<%= fields_for(@financer) do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
<% end %>

app/views/financers/edit.html.erb
<h1>Editing Financer</h1>

<%= render 'form' %>

<%= link_to 'Show', @financer %> |
<%= link_to 'Back', financers_path %>

app/views/financers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Financers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @financers.each do |financer| %>
      <tr>
        <td><%= financer.name %></td>
        <td><%= link_to 'Show', financer %></td>
        <td><%= link_to 'Edit', edit_financer_path(financer) %></td>
        <td><%= link_to 'Destroy', financer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Financer', new_financer_path %>

app/views/financers/new.html.erb
<h1>New Financer</h1>

<%= render 'form' %>

<%= link_to 'Back', financers_path %>

app/views/financers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @financer.name %>
</p>

<%= link_to 'Edit', edit_financer_path(@financer) %> |
<%= link_to 'Back', financers_path %>