config/routes.rb
Rails.application.routes.draw do
  resources :financers
  resources :individuals
  resources :companies
  resources :my_customers

end

app/models/individual.rb
class Individual < ActiveRecord::Base
  has_one :my_customer, as: :tradeable
  after_save :ensure_my_customer

  def ensure_my_customer
    if self.my_customer.nil?
      my_customer = MyCustomer.new(number: "#{self.class}-#{self.class.count}")
      my_customer.tradeable = self
      my_customer.save!
    end
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def description
    self.full_name
  end

end

app/controllers/individuals_controller.rb
class IndividualsController < ApplicationController
  before_action :set_individual, only: [:show, :edit, :update, :destroy]

  # GET /individuals
  # GET /individuals.json
  def index
    @individuals = Individual.all
  end

  # GET /individuals/1
  # GET /individuals/1.json
  def show
  end

  # GET /individuals/new
  def new
    @individual = Individual.new
  end

  # GET /individuals/1/edit
  def edit
  end

  # POST /individuals
  # POST /individuals.json
  def create
    saved = false
    begin
      ActiveRecord::Base.transaction do
        @individual = Individual.new(individual_params)
        @individual.save!
        saved = true
      end
    rescue ActiveRecord::RecordInvalid
    end

    respond_to do |format|
      if saved
        format.html { redirect_to @individual, notice: 'Individual was successfully created.' }
        format.json { render :show, status: :created, location: @individual }
      else
        format.html { render :new }
        format.json { render json: @individual.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /individuals/1
  # PATCH/PUT /individuals/1.json
  def update
    respond_to do |format|
      if @individual.update(individual_params)
        format.html { redirect_to @individual, notice: 'Individual was successfully updated.' }
        format.json { render :show, status: :ok, location: @individual }
      else
        format.html { render :edit }
        format.json { render json: @individual.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /individuals/1
  # DELETE /individuals/1.json
  def destroy
    @individual.destroy
    respond_to do |format|
      format.html { redirect_to individuals_url, notice: 'Individual was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_individual
      @individual = Individual.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def individual_params
      params.require(:individual).permit(:first_name, :last_name)
    end
end

app/helpers/individuals_helper.rb
module IndividualsHelper
end

app/views/individuals/_form.html.erb
<%= form_for(@individual) do |f| %>
  <% if @individual.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@individual.errors.count, "error") %> prohibited this individual from being saved:</h2>

      <ul>
      <% @individual.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_area :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_area :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/individuals/_partial_form.html.erb
<%= fields_for(@individual) do |f| %>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_area :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_area :last_name %>
  </div>
<% end %>

app/views/individuals/edit.html.erb
<h1>Editing Individual</h1>

<%= render 'form' %>

<%= link_to 'Show', @individual %> |
<%= link_to 'Back', individuals_path %>

app/views/individuals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Individuals</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @individuals.each do |individual| %>
      <tr>
        <td><%= individual.first_name %></td>
        <td><%= individual.last_name %></td>
        <td><%= link_to 'Show', individual %></td>
        <td><%= link_to 'Edit', edit_individual_path(individual) %></td>
        <td><%= link_to 'Destroy', individual, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Individual', new_individual_path %>

app/views/individuals/new.html.erb
<h1>New Individual</h1>

<%= render 'form' %>

<%= link_to 'Back', individuals_path %>

app/views/individuals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @individual.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @individual.last_name %>
</p>

<%= link_to 'Edit', edit_individual_path(@individual) %> |
<%= link_to 'Back', individuals_path %>